## 1
name: SignAndroidRelease
## Actions that will be executed when you push code currently none
on:
  push:

## 2
jobs:
  ## 3
  SignAndroidRelease:
    runs-on: [ubuntu-latest]
    steps:
        - name: Sign Android release
          uses: r0adkll/sign-android-release@v1
